### ISSUE TITLE
Erro na tela de Login

### ISSUE THREAD

**Issue by easyfragx10** [ramonsilvanet/controle-frota-php#2]
Boa Tarde!

Fui realizar um teste com o sistema e após realizar os procedimentos de instalação, quando acesso a url da pagina index é me mostrado um erro.
Poderiam me auxiliar por gentileza?Segue abaixo o erro.
`A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257`

**Comment by ramonsilvanet** [comment]
Boa tarde, esse erro ocorre por causa de incompatibilidade desta versão do framework com as versões mais atuais do PHP.

Você pode corrigir de 3 maneiras diferentes:

1. Atualizar o framework. Vá em https://codeigniter.com/download baixe uma versão mais nova do framework e atualize a pasta system com os arquivos baixados. Por se tratar de uma atualização muito grande, há chances de surgirem outros problemas.

2. Fazer downgrade da versão do PHP. Esse sistema foi feito na época do php 5.2.5. Eu lembro que a prima versão do php já dava problemas

3. Corrigir o erro manualmente. Vá no  arquivo https://github.com/ramonsilvanet/controle-frota-php/blob/master/system/core/Common.php e na linha 257 substitua :

`return $_config[0] =& $config;`
por 
```
$config[0] =& config;
return $config[0];
```

**Comment by easyfragx10** [comment]
Obrigado pela Ajuda!
Se eu instalar essa versão do php as funcionalidades do projeto estarão ok?

Em 27 de julho de 2017 13:05, Ramon Ferreira Silva <notifications@github.com

**Comment by ramonsilvanet** [comment]
Sim o PHP 5.2.5 e compatível com o sistema. Lembrando que esse sistema não
está completo. Mas tudo que existe vai funcionar

Em 27 de jul de 2017 17:51, "easyfragx10" <notifications@github.com>
escreveu:

**Comment by easyfragx10** [comment]
Muito Obrigado mesmo pela ajuda rápida!
Fico muito agradecido estou fazendo um estagio na prefeitura da minha
cidade e queriam um sistema de controle de frotas.
Pelo oque eu vi tem bastante coisa no projeto, vou instalar a versão 5.2.5
pra ver melhor.
Você se lembra se a parte de veículos manutenção estava completa?


Em 27 de julho de 2017 17:53, Ramon Ferreira Silva <notifications@github.com

**Comment by ramonsilvanet** [comment]
Não estava, foi justo onde eu parei, manutenção e abastecimento. Acho que
basicamente está com os cadastros

Em 27 de jul de 2017 18:06, "easyfragx10" <notifications@github.com>
escreveu:

**Comment by easyfragx10** [comment]
Entendi, Muito Obrigado!
Tenha uma boa noite!

Em 27 de julho de 2017 18:07, Ramon Ferreira Silva <notifications@github.com
